-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Adresler"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriId" integer NOT NULL,
    "AdresDetay" character varying(250) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Bilancolar"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriId" integer NOT NULL,
    "Tarih" date NOT NULL,
    "Tutar" money NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."GercekMusteriler"
(
    "MusteriId" integer NOT NULL,
    "Ad" character varying(50) NOT NULL,
    "Soyad" character varying(50) NOT NULL,
    "TcKimlikNo" character(11) NOT NULL,
    PRIMARY KEY ("MusteriId")
);

CREATE TABLE public."Kanallar"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "KanalAdi" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Musteriler"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MusteriNo" character(10) NOT NULL,
    "KanalId" integer NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Sendikalar"
(
    "MusteriId" integer NOT NULL,
    "Ad" character varying(50) NOT NULL,
    PRIMARY KEY ("MusteriId")
);

CREATE TABLE public."TicariFaliyetler"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "GercekMusteriId" integer NOT NULL,
    "BaslangicTarihi" date NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."TuzelMusteriler"
(
    "MusteriId" integer NOT NULL,
    "Unvan" character varying(50) NOT NULL,
    "VergiNo" character(10) NOT NULL,
    PRIMARY KEY ("MusteriId")
);

ALTER TABLE public."Adresler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."Bilancolar"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."GercekMusteriler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."Musteriler"
    ADD FOREIGN KEY ("KanalId")
    REFERENCES public."Kanallar" ("Id")
    NOT VALID;


ALTER TABLE public."Sendikalar"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;


ALTER TABLE public."TicariFaliyetler"
    ADD FOREIGN KEY ("GercekMusteriId")
    REFERENCES public."GercekMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."TuzelMusteriler"
    ADD FOREIGN KEY ("MusteriId")
    REFERENCES public."Musteriler" ("Id")
    NOT VALID;

END;